//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NukaCollect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NukaCollect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string ActiveRent {
            get {
                return ResourceManager.GetString("ActiveRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Formats 的本地化字符串。
        /// </summary>
        public static string AllFormats {
            get {
                return ResourceManager.GetString("AllFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspect Ratio 的本地化字符串。
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Birth Date 的本地化字符串。
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue-Ray 的本地化字符串。
        /// </summary>
        public static string BlueRay {
            get {
                return ResourceManager.GetString("BlueRay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Card Number 的本地化字符串。
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments 的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut-Price 的本地化字符串。
        /// </summary>
        public static string CutPriceMovieCategoryName {
            get {
                return ResourceManager.GetString("CutPriceMovieCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damaged 的本地化字符串。
        /// </summary>
        public static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Access (.mdb) 的本地化字符串。
        /// </summary>
        public static string DBFormatMdb {
            get {
                return ResourceManager.GetString("DBFormatMdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Server 的本地化字符串。
        /// </summary>
        public static string DBFormatSql {
            get {
                return ResourceManager.GetString("DBFormatSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string DefaultMovieCategoryName {
            get {
                return ResourceManager.GetString("DefaultMovieCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directors 的本地化字符串。
        /// </summary>
        public static string Directors {
            get {
                return ResourceManager.GetString("Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discount Level 的本地化字符串。
        /// </summary>
        public static string DiscountLevel {
            get {
                return ResourceManager.GetString("DiscountLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DVD 的本地化字符串。
        /// </summary>
        public static string DVD {
            get {
                return ResourceManager.GetString("DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genre 的本地化字符串。
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Late Fees 的本地化字符串。
        /// </summary>
        public static string LateFees {
            get {
                return ResourceManager.GetString("LateFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lost 的本地化字符串。
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Releases 的本地化字符串。
        /// </summary>
        public static string NewReleasesPriceMovieCategoryName {
            get {
                return ResourceManager.GetString("NewReleasesPriceMovieCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overdue 的本地化字符串。
        /// </summary>
        public static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchases 的本地化字符串。
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rentals 的本地化字符串。
        /// </summary>
        public static string Rentals {
            get {
                return ResourceManager.GetString("Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rented 的本地化字符串。
        /// </summary>
        public static string Rented {
            get {
                return ResourceManager.GetString("Rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Renter 的本地化字符串。
        /// </summary>
        public static string RenterActive {
            get {
                return ResourceManager.GetString("RenterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Renter 的本地化字符串。
        /// </summary>
        public static string RenterBasic {
            get {
                return ResourceManager.GetString("RenterBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First-Time Renter 的本地化字符串。
        /// </summary>
        public static string RenterFirstTime {
            get {
                return ResourceManager.GetString("RenterFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occasional Renter 的本地化字符串。
        /// </summary>
        public static string RenterOccasional {
            get {
                return ResourceManager.GetString("RenterOccasional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prodigious Renter 的本地化字符串。
        /// </summary>
        public static string RenterProdigious {
            get {
                return ResourceManager.GetString("RenterProdigious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Time 的本地化字符串。
        /// </summary>
        public static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shelf {0} 的本地化字符串。
        /// </summary>
        public static string ShelfPattern {
            get {
                return ResourceManager.GetString("ShelfPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sold 的本地化字符串。
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL server authentication 的本地化字符串。
        /// </summary>
        public static string SqlAuthenticationTypeSql {
            get {
                return ResourceManager.GetString("SqlAuthenticationTypeSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows authentication 的本地化字符串。
        /// </summary>
        public static string SqlAuthenticationTypeWin {
            get {
                return ResourceManager.GetString("SqlAuthenticationTypeWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video CD 的本地化字符串。
        /// </summary>
        public static string VideoCD {
            get {
                return ResourceManager.GetString("VideoCD", resourceCulture);
            }
        }
    }
}
