//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NukaCollect.Reports.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NukaCollect.Reports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active Customers 的本地化字符串。
        /// </summary>
        public static string ActiveCustomerReport {
            get {
                return ResourceManager.GetString("ActiveCustomerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Cards 的本地化字符串。
        /// </summary>
        public static string CustomerCardsReport {
            get {
                return ResourceManager.GetString("CustomerCardsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customers: 的本地化字符串。
        /// </summary>
        public static string CustomersCaption {
            get {
                return ResourceManager.GetString("CustomersCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details: 的本地化字符串。
        /// </summary>
        public static string DetailsCaption {
            get {
                return ResourceManager.GetString("DetailsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date: 的本地化字符串。
        /// </summary>
        public static string EndDateCaption {
            get {
                return ResourceManager.GetString("EndDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movie Inventory 的本地化字符串。
        /// </summary>
        public static string FilmCardsReport {
            get {
                return ResourceManager.GetString("FilmCardsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movie Rentals by Customer 的本地化字符串。
        /// </summary>
        public static string FilmRentsReport {
            get {
                return ResourceManager.GetString("FilmRentsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Most Profitable Genres 的本地化字符串。
        /// </summary>
        public static string GenresReport {
            get {
                return ResourceManager.GetString("GenresReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Time Span: 的本地化字符串。
        /// </summary>
        public static string LastTimeCaption {
            get {
                return ResourceManager.GetString("LastTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movies: 的本地化字符串。
        /// </summary>
        public static string MoviesCaption {
            get {
                return ResourceManager.GetString("MoviesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Custom) 的本地化字符串。
        /// </summary>
        public static string PeriodCustom {
            get {
                return ResourceManager.GetString("PeriodCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 Years 的本地化字符串。
        /// </summary>
        public static string PeriodFiveYears {
            get {
                return ResourceManager.GetString("PeriodFiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string PeriodMonth {
            get {
                return ResourceManager.GetString("PeriodMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 Months 的本地化字符串。
        /// </summary>
        public static string PeriodSixMonths {
            get {
                return ResourceManager.GetString("PeriodSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 Years 的本地化字符串。
        /// </summary>
        public static string PeriodTenYears {
            get {
                return ResourceManager.GetString("PeriodTenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 Months 的本地化字符串。
        /// </summary>
        public static string PeriodThreeMonths {
            get {
                return ResourceManager.GetString("PeriodThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 Years 的本地化字符串。
        /// </summary>
        public static string PeriodTwoYears {
            get {
                return ResourceManager.GetString("PeriodTwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        public static string PeriodYear {
            get {
                return ResourceManager.GetString("PeriodYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revenue: {0}{1} 的本地化字符串。
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date: 的本地化字符串。
        /// </summary>
        public static string StartDateCaption {
            get {
                return ResourceManager.GetString("StartDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Rentals 的本地化字符串。
        /// </summary>
        public static string TopFilmsReport {
            get {
                return ResourceManager.GetString("TopFilmsReport", resourceCulture);
            }
        }
    }
}
